<?php

namespace splitbrain\dokuwiki\plugin\smtp;

/**
 * Class TokenStore
 *
 * Persists the OAuth 2.0 tokens obtained for SMTP authentication.
 *
 * The data is kept in a single JSON file below DokuWiki's meta directory. That
 * directory is not served by the webserver, so the long lived refresh token is
 * not exposed. The tokens deliberately live outside the plugin configuration
 * because the configuration is regenerated by the config manager and is not a
 * good place for values obtained at runtime.
 *
 * @package splitbrain\dokuwiki\plugin\smtp
 */
class TokenStore
{
    /** @var string absolute path to the JSON storage file */
    protected $file;

    /** @var array|null in memory cache of the decoded data */
    protected $data;

    /**
     * @param string $file absolute path to the storage file, defaults to the meta directory
     */
    public function __construct($file = '')
    {
        if ($file === '') {
            global $conf;
            $file = $conf['metadir'] . '/_smtp_oauth.json';
        }
        $this->file = $file;
    }

    /**
     * Read the whole stored data set
     *
     * @return array
     */
    public function getAll()
    {
        if ($this->data === null) {
            $json = io_readFile($this->file, false);
            $this->data = $json ? (json_decode($json, true) ?: array()) : array();
        }
        return $this->data;
    }

    /**
     * Get a single stored value
     *
     * @param string $key
     * @param mixed $default
     * @return mixed
     */
    public function get($key, $default = null)
    {
        $data = $this->getAll();
        return $data[$key] ?? $default;
    }

    /**
     * Merge the given values into the stored data and persist them
     *
     * @param array $values
     * @return void
     */
    public function set(array $values)
    {
        $data = array_merge($this->getAll(), $values);
        $this->data = $data;
        io_saveFile($this->file, json_encode($data, JSON_PRETTY_PRINT));
    }

    /**
     * Remove all stored tokens (disconnect)
     *
     * @return void
     */
    public function clear()
    {
        $this->data = array();
        @unlink($this->file);
    }

    /**
     * Is a refresh token stored?
     *
     * @return bool
     */
    public function isAuthorized()
    {
        return (bool) $this->get('refresh_token');
    }
}
